#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_SOLR_IP:8080

nohup $OPENSHIFT_REPO_DIR/solr/testrubyserver.rb $OPENSHIFT_SOLR_IP $OPENSHIFT_REPO_DIR/solr > $OPENSHIFT_SOLR_DIR/logs/server.log 2>&1 &
